name: Build

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Copy code to PROD
      run: jsonlint-php -q styles/*.json >/dev/null 2>&1 && (cp -r . ${{ secrets.PROD_DIR }} 2>/dev/null;echo "Deployed") || (echo "JSON not correct"; exit 1)
    - name: Status message to Mattermost
      run: |
        STATUS=$(ls)
        curl -i -X POST -H 'Content-Type: application/json' -d "{\"text\":\"$STATUS\"}" ${{ secrets.MATTERMOST_WEBHOOK_URL }}
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
      
