name: Mattermost

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Status message to Mattermost
      run: |
        STATUS=$(git log --name-status HEAD^..HEAD|sed s'/"/\'/g');
        echo "{\"text\":\"$STATUS\"}" > mattermost.json
    - uses: mattermost/action-mattermost-notify@master
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
